version: "3.3"
services:
  app:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    links: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - 27017:27017
