version: "3.3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./log:/app/log
    environment:
        - MONGO_HOST=mongo
        - MONGO_USERNAME=admin
        - MONGO_PASSWORD=password
    links:
      - mongo
  mongo:
    image: mongo:4.2
    volumes:
      - ./db:/data/db
      - ./init-mongo-user.js:/docker-entrypoint-initdb.d/init-mongo-user.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=origami
    ports:
      - 27017:27017
